export const messages = {
  custmerCreated: "Customer Details Created Successfully",
  caseCreated: "Case Details Created Successfully",
  policyCreated: "Policy Details Created Successfully",
  vehicleCreated: "Vehicle details created successfully",
  documentUploaded: "Document uploaded successfully",
  documentNotFound: "Document not found",
  noDocumentuploaded: "No document uploaded",
  createdByOrUpdatedByRequired: "createdBy and updatedBy are required.",
  duplicateEmail: "Email already exists for this lead.",
  duplicatePhone: "Phone number already exists for this lead.",
  invalidEmail: "Invalid email format.",
  caseNotFound: "Case not found.",
  policyNotFound: "Policy not found.",
  vehicleNotFound: "Vehicle not found.",
  customerNotFound: "Customer not found.",
  caseUpdated: "Case Details Updated Successfully",
  policyUpdated: "Policy Details Updated Successfully",
  vehicleUpdated: "Vehicle Details Updated Successfully",
  caseRetrieved: "Case Details Retrieved Successfully",
  policyRetrieved: "Policy Details Retrieved Successfully",
  vehicleRetrieved: "Vehicle Details Retrieved Successfully",
  customerRetrieved: "Customer Details Retrieved Successfully",
  invalidLeadId: "Invalid Lead ID format.",
  customerDetailsNotFound: "Customer details not found for the given lead ID.",
  caseDetailsNotFound: "Case details not found for the given lead ID.",
  caseDeleted: "Case Details Deleted Successfully",
  policyDeleted: "Policy Details Deleted Successfully",
  vehicleDeleted: "Vehicle Details Deleted Successfully",
  invalidCaseId: "Invalid Case ID format.",
  invalidPolicyId: "Invalid Policy ID format.",
  invalidVehicleId: "Invalid Vehicle ID format.",
  casesRetrieved: "All Case Details Retrieved Successfully",
  caseIdRequired: "Case ID is required for this operation.",
  invalidCustomerId: "Invalid Customer ID format.",
  customerUpdated: "Customer Details Updated Successfully",
  customerIdRequired: "Customer ID is required for this operation.",
  customersRetrieved: "All Customer Details Retrieved Successfully",
  customerDeleted: "Customer Details Deleted Successfully",
  customerDetailsCreated: "Customer Details Created Successfully",
  customerDetailsUpdated: "Customer Details Updated Successfully",
  invalidId: "Invalid ID format.",
  noPoliciesFound: "No Policy Details Found.",
  policiesRetrieved: "All Policy Details Retrieved Successfully",
  vehiclesRetrieved: "All Vehicle Details Retrieved Successfully",
  invalidDraftId: "Invalid Draft ID or case not found.",
  userIdRequired: "User ID is required for this operation.",
  quotationCreated:"Quotation is created Successfully",
  leadIdRequired: "Lead Id is required",
  quotationRetrieved: "All Quotation Details Retrieved Successfully",
  quotationNotFound: "Quotation not found",
  quotationUpdated:"Quotation Updated Successfully",
  quotationDeleted: "Quotation Deleted Successfully",
}