export const messages = {
  userNotFound: "User not found",
  invalidEmail: "Invalid email format",
  invalidPhone: "Invalid phone number",
  weakPassword: "Password must be stronger",
  userExists: "Email already in use",
  serverError: "Server error",
  invalidCredentialsEmail: "Invalid email",
  invalidCredentialsPassword: "Invalid password",
  loginSuccess: "Login successful",
  leadCreated: "Lead created successfully",
  leadUpdated: "Lead updated successfully",
  leadDeleted: "Lead deleted successfully",
  leadNotFound: "Lead not found",
  getLead: "Lead retrieved successfully",
  leadFollowUpNotFound: "Lead follow-up not found",
  leadFollowUpDeleted: "Lead follow-up deleted successfully",
  leadFollowUpRetrieved: "Lead follow-up retrieved successfully",
  leadFollowUpCreated: "Lead follow-up created successfully",
  leadFollowUpUpdated: "Lead follow-up updated successfully",
  noteCreated:"Note created successfully",
  invalidNotesId: "Invalid note ID",
  noteNotFound:"Note not found",
  noteUpdated:"Note updated successfully",
  noteDeleted:"Note deleted successfully",
  notesRetrieved:"Notes retrieved successfully",
  saleCreated:"Sale created successfully",
  salesmanBookingCreated: "Salesman Booking created successfully",
  salesRetrieved:"Sales retrieved successfully",
  saleNotFound: "Sale retrieved successfully",
  saleDeleted:"Sale deleted successfully",
  getHistories: "All histories retrieved",  
  defaultmessage:"Server running sucessfully!",
  salesmanNotFound:"Salesman not found",
  salesmanBookingUpdated:"Salesman booking updated sucessfully",
  salesmanBookingDelete:"salesman booking deleted successfully",
  salesmanBookingRetrieved:"salesman booking retrieved successfully",
  invalidStatus:"Invalid lead status provided",
  leadStatusUpdated: "Lead status updated successfully",
  leadStatusNotFound: "Lead status not found",  
  leadStatusDeleted: "Lead status deleted successfully",
  leadStatusCreated: "Lead status created successfully",
  leadStatusRetrieved: "Lead status retrieved successfully",
  bookingNotFound: "Booking not found",
  bookingUpdated: "Booking updated successfully",
  bookingDeleted: "Booking deleted successfully",
  bookingCreationFailed: "Failed to create booking",
  bookingUpdateFailed: "Failed to update booking",
  bookingDeletionFailed: "Failed to delete booking",
  invalidBookingId: "Invalid booking ID",
  bookingRetrieved: "Booking retrieved successfully",
  bookingRetrievalFailed: "Failed to retrieve booking",
  bookingCreated: "Booking created successfully",
  leadBookingsRetrieved: "Lead bookings retrieved successfully",
  leadBookingNotFound: "Lead booking not found",
  leadBookingDeleted: "Lead booking deleted successfully",
  leadBookingsRetrievalFailed: "Failed to retrieve lead bookings",
  leadBookingCreationFailed: "Failed to create lead booking",
  leadBookingUpdateFailed: "Failed to update lead booking",
  leadBookingCreated: "Lead booking created successfully",
  leadBookingUpdated: "Lead booking updated successfully",
  leadFollowUpRetrievalFailed: "Failed to retrieve lead follow-up",
  leadFollowUpCreationFailed: "Failed to create lead follow-up",
  leadFollowUpUpdateFailed: "Failed to update lead follow-up",
  duplicateEmail: "A lead with this email already exists",
  deleteBynotfound:"Deleted By fields is required"
};
